#!/usr/bin/env node
// Emits bin/tokens.mjs from src/tokens.css, so canon-lint can tell a real
// token from a typo. Run by scripts/build.sh.
//
// This exists because a misspelled custom property is silent. `--color-brnd`
// in a theme file is valid CSS, overrides nothing, and produces a page that
// looks almost right. Nobody notices until someone asks why the brand colour
// only applies in some places.

import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync('src/tokens.css', 'utf-8');

// Definitions only: a declaration at the start of a line inside :root or a
// theme block. Uses inside var() are deliberately not collected.
const names = new Set();
for (const m of src.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gm)) names.add(m[1]);

const sorted = [...names].sort();
writeFileSync(
  'bin/tokens.mjs',
  `// Generated by scripts/gen-tokens.mjs from src/tokens.css. Do not edit.\n` +
    `export const TOKENS = new Set(${JSON.stringify(sorted, null, 2)});\n`,
);
console.log(`✓ Built bin/tokens.mjs (${sorted.length} tokens)`);
